import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { PageHeader, StateMessage } from '../../components/common/PageHeader';
import { StatusBadge } from '../../components/common/StatusBadge';
import { Toast } from '../../components/common/Toast';
import { projectService } from '../../services';
import { milestone3Api, type ApiInvoice, type ApiOrder, type ApiRequest, type ApiVendor } from '../../services/milestone3';
import { useAuth } from '../../hooks/useAuth';
import type { Project } from '../../types';

type Tab='Requests'|'Vendors'|'Purchase Orders'|'Invoices';
export function ProcurementPage(){
  const {user}=useAuth();const canManage=user?.role==='Administrator'||user?.role==='Project Manager';
  const [tab,setTab]=useState<Tab>('Requests');const [requests,setRequests]=useState<ApiRequest[]>([]);const [vendors,setVendors]=useState<ApiVendor[]>([]);const [orders,setOrders]=useState<ApiOrder[]>([]);const [invoices,setInvoices]=useState<ApiInvoice[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [error,setError]=useState('');const [toast,setToast]=useState('');const [search,setSearch]=useState('');
  const [projectId,setProjectId]=useState('');const [item,setItem]=useState('');const [qty,setQty]=useState('1');const [cost,setCost]=useState('');const [supplier,setSupplier]=useState('');const [notes,setNotes]=useState('');
  const [vendorName,setVendorName]=useState('');const [vendorEmail,setVendorEmail]=useState('');const [vendorPhone,setVendorPhone]=useState('');
  const [orderVendor,setOrderVendor]=useState('');const [orderRequest,setOrderRequest]=useState('');const [orderAmount,setOrderAmount]=useState('');const [delivery,setDelivery]=useState('');
  const [invoiceOrder,setInvoiceOrder]=useState('');const [invoiceNumber,setInvoiceNumber]=useState('');const [invoiceAmount,setInvoiceAmount]=useState('');
  async function reload(){setError('');try{const [r,v,o,i]=await Promise.all([milestone3Api.requests(),milestone3Api.vendors(),milestone3Api.orders(),milestone3Api.invoices()]);setRequests(r);setVendors(v);setOrders(o);setInvoices(i)}catch(e){setError(e instanceof Error?e.message:'Could not load procurement data')}}
  useEffect(()=>{void reload();projectService.list().then(rows=>{setProjects(rows);if(rows.length)setProjectId(rows[0].id)}).catch(e=>setError(e.message))},[]);
  const filteredRequests=useMemo(()=>requests.filter(x=>`${x.item_name} ${x.supplier_name??''} ${x.status}`.toLowerCase().includes(search.toLowerCase())),[requests,search]);
  async function createRequest(e:FormEvent){e.preventDefault();try{const row=await milestone3Api.createRequest({project_id:Number(projectId),item_name:item,quantity:Number(qty),unit:'units',estimated_cost:Number(cost||0),supplier_name:supplier||null,notes:notes||null});setRequests(rows=>[row,...rows]);setItem('');setQty('1');setCost('');setNotes('');setToast('Procurement request created.')}catch(e){setError(e instanceof Error?e.message:'Could not create request')}}
  async function createVendor(e:FormEvent){e.preventDefault();try{const row=await milestone3Api.createVendor({name:vendorName,email:vendorEmail||null,phone:vendorPhone||null});setVendors(rows=>[row,...rows]);setVendorName('');setVendorEmail('');setVendorPhone('');setToast('Vendor created.')}catch(e){setError(e instanceof Error?e.message:'Could not create vendor')}}
  async function createOrder(e:FormEvent){e.preventDefault();try{const row=await milestone3Api.createOrder({project_id:Number(projectId),vendor_id:Number(orderVendor),procurement_id:orderRequest?Number(orderRequest):null,total_amount:Number(orderAmount||0),expected_delivery_date:delivery?new Date(delivery).toISOString():null,notes:null});setOrders(rows=>[row,...rows]);await reload();setToast(`Purchase order ${row.po_number} created.`)}catch(e){setError(e instanceof Error?e.message:'Could not create order')}}
  async function createInvoice(e:FormEvent){e.preventDefault();try{const row=await milestone3Api.createInvoice({purchase_order_id:Number(invoiceOrder),invoice_number:invoiceNumber,amount:Number(invoiceAmount),status:'pending',invoice_date:null,due_date:null,notes:null});setInvoices(rows=>[row,...rows]);setInvoiceNumber('');setInvoiceAmount('');setToast('Invoice recorded.')}catch(e){setError(e instanceof Error?e.message:'Could not create invoice')}}
  async function changeStatus(id:number,status:string){try{const row=await milestone3Api.setRequestStatus(id,status);setRequests(rows=>rows.map(x=>x.id===id?row:x));setToast(`Request ${status}.`)}catch(e){setError(e instanceof Error?e.message:'Status update failed')}}
  async function deleteRequest(id:number){try{await milestone3Api.deleteRequest(id);setRequests(rows=>rows.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:'Delete failed')}}
  async function deleteVendor(id:number){try{await milestone3Api.deleteVendor(id);setVendors(rows=>rows.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:'Vendor could not be deleted')}}
  return <><PageHeader title="Procurement" subtitle="Manage requests, approved suppliers, purchase orders and invoices."/>
    {error&&<div className="alert alert-danger" role="alert">{error}<button className="btn btn-sm btn-link" onClick={()=>void reload()}>Retry</button></div>}
    <div className="row g-3 mb-4">{[['Total Requests',requests.length],['Pending',requests.filter(x=>x.status==='pending').length],['Approved',requests.filter(x=>x.status==='approved').length],['Purchase Orders',orders.length],['Invoices',invoices.length]].map(([label,value])=><div className="col-6 col-xl" key={label}><div className="bt-card bt-card-pad"><p className="bt-label mb-1">{label}</p><strong className="h3 mb-0">{value}</strong></div></div>)}</div>
    <nav className="d-flex gap-2 flex-wrap mb-3">{(['Requests','Vendors','Purchase Orders','Invoices'] as Tab[]).map(x=><button key={x} className={`bt-pill-tab ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{x}</button>)}</nav>
    {tab==='Requests'&&<><section className="bt-card bt-card-pad mb-3"><h2 className="h5">New procurement request</h2><form className="row g-2 align-items-end" onSubmit={createRequest}>
      <div className="col-12 col-md-3"><label className="form-label">Project</label><select className="form-select" value={projectId} onChange={e=>setProjectId(e.target.value)} required>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
      <div className="col-12 col-md-3"><label className="form-label">Item</label><input className="form-control" value={item} onChange={e=>setItem(e.target.value)} required maxLength={255}/></div>
      <div className="col-6 col-md-1"><label className="form-label">Qty</label><input className="form-control" type="number" min="0.01" step="any" value={qty} onChange={e=>setQty(e.target.value)} required/></div>
      <div className="col-6 col-md-2"><label className="form-label">Est. cost</label><input className="form-control" type="number" min="0" step="any" value={cost} onChange={e=>setCost(e.target.value)}/></div>
      <div className="col-12 col-md-2"><label className="form-label">Supplier name</label><input className="form-control" value={supplier} onChange={e=>setSupplier(e.target.value)}/></div>
      <div className="col-12 col-md-1"><button className="btn btn-accent w-100">Submit</button></div>
    </form></section><section className="bt-card"><div className="p-3"><input className="form-control" placeholder="Search requests" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filteredRequests.length===0?<StateMessage icon="bi-cart" title="No procurement requests" message="Create a request to start the procurement workflow."/>:<div className="table-responsive"><table className="bt-table"><thead><tr><th>Item</th><th>Project</th><th>Quantity</th><th>Estimated</th><th>Supplier</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filteredRequests.map(r=><tr key={r.id}><td>{r.item_name}</td><td>{projects.find(p=>Number(p.id)===r.project_id)?.name??`Project ${r.project_id}`}</td><td>{r.quantity} {r.unit}</td><td>{Number(r.estimated_cost).toLocaleString()}</td><td>{r.supplier_name||'—'}</td><td><StatusBadge status={r.status}/></td><td>{canManage&&r.status==='pending'?<><button className="btn btn-sm btn-outline-success me-1" onClick={()=>void changeStatus(r.id,'approved')}>Approve</button><button className="btn btn-sm btn-outline-warning me-1" onClick={()=>void changeStatus(r.id,'rejected')}>Reject</button></>:null}<button className="btn btn-sm btn-outline-danger" onClick={()=>void deleteRequest(r.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></>}
    {tab==='Vendors'&&<><section className="bt-card bt-card-pad mb-3"><h2 className="h5">Add vendor</h2><form className="row g-2 align-items-end" onSubmit={createVendor}><div className="col-12 col-md-4"><label className="form-label">Company name</label><input className="form-control" value={vendorName} onChange={e=>setVendorName(e.target.value)} required/></div><div className="col-12 col-md-3"><label className="form-label">Email</label><input className="form-control" type="email" value={vendorEmail} onChange={e=>setVendorEmail(e.target.value)}/></div><div className="col-12 col-md-3"><label className="form-label">Phone</label><input className="form-control" value={vendorPhone} onChange={e=>setVendorPhone(e.target.value)}/></div><div className="col-12 col-md-2"><button disabled={!canManage} className="btn btn-accent w-100">Create vendor</button></div></form></section><section className="bt-card"><table className="bt-table"><thead><tr><th>Vendor</th><th>Contact</th><th>Email</th><th>Category</th><th>Status</th><th>Actions</th></tr></thead><tbody>{vendors.map(v=><tr key={v.id}><td>{v.name}</td><td>{v.contact_person||v.phone||'—'}</td><td>{v.email||'—'}</td><td>{v.category||'—'}</td><td><StatusBadge status={v.status}/></td><td>{canManage&&<><button className="btn btn-sm btn-outline-secondary me-1" onClick={()=>{const name=window.prompt('Vendor name',v.name);if(name?.trim())void milestone3Api.updateVendor(v.id,{name}).then(updated=>setVendors(rows=>rows.map(x=>x.id===v.id?updated:x))).catch(e=>setError(e.message))}}>Edit</button>{user?.role==='Administrator'&&<button className="btn btn-sm btn-outline-danger" onClick={()=>void deleteVendor(v.id)}>Delete</button>}</>}</td></tr>)}</tbody></table></section></>}
    {tab==='Purchase Orders'&&<><section className="bt-card bt-card-pad mb-3"><h2 className="h5">Create purchase order</h2><form className="row g-2 align-items-end" onSubmit={createOrder}><div className="col-6 col-md-3"><label className="form-label">Vendor</label><select className="form-select" value={orderVendor} onChange={e=>setOrderVendor(e.target.value)} required><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div><div className="col-6 col-md-3"><label className="form-label">Request</label><select className="form-select" value={orderRequest} onChange={e=>setOrderRequest(e.target.value)}><option value="">None</option>{requests.map(r=><option key={r.id} value={r.id}>{r.item_name} ({r.status})</option>)}</select></div><div className="col-6 col-md-2"><label className="form-label">Project</label><select className="form-select" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="col-6 col-md-2"><label className="form-label">Total amount</label><input className="form-control" type="number" min="0" step="any" value={orderAmount} onChange={e=>setOrderAmount(e.target.value)} required/></div><div className="col-6 col-md-1"><label className="form-label">Delivery</label><input className="form-control" type="date" value={delivery} onChange={e=>setDelivery(e.target.value)}/></div><div className="col-6 col-md-1"><button className="btn btn-accent w-100" disabled={!canManage}>Create</button></div></form></section><section className="bt-card"><table className="bt-table"><thead><tr><th>PO #</th><th>Project</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Delivery</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.po_number}</td><td>{projects.find(p=>Number(p.id)===o.project_id)?.name??o.project_id}</td><td>{vendors.find(v=>v.id===o.vendor_id)?.name??o.vendor_id}</td><td>{Number(o.total_amount).toLocaleString()}</td><td><StatusBadge status={o.status}/></td><td>{o.expected_delivery_date?.slice(0,10)||'—'}</td></tr>)}</tbody></table></section></>}
    {tab==='Invoices'&&<><section className="bt-card bt-card-pad mb-3"><h2 className="h5">Record invoice</h2><form className="row g-2 align-items-end" onSubmit={createInvoice}><div className="col-12 col-md-4"><label className="form-label">Purchase order</label><select className="form-select" value={invoiceOrder} onChange={e=>setInvoiceOrder(e.target.value)} required><option value="">Select order</option>{orders.map(o=><option key={o.id} value={o.id}>{o.po_number} — {o.total_amount}</option>)}</select></div><div className="col-12 col-md-3"><label className="form-label">Invoice number</label><input className="form-control" value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)} required/></div><div className="col-12 col-md-3"><label className="form-label">Amount</label><input className="form-control" type="number" min="0.01" step="any" value={invoiceAmount} onChange={e=>setInvoiceAmount(e.target.value)} required/></div><div className="col-12 col-md-2"><button className="btn btn-accent w-100" disabled={!canManage}>Record</button></div></form></section><section className="bt-card"><table className="bt-table"><thead><tr><th>Invoice</th><th>Purchase order</th><th>Amount</th><th>Issued</th><th>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoice_number}</td><td>{orders.find(o=>o.id===i.purchase_order_id)?.po_number??i.purchase_order_id}</td><td>{Number(i.amount).toLocaleString()}</td><td>{i.invoice_date?.slice(0,10)||'—'}</td><td><StatusBadge status={i.status}/></td></tr>)}</tbody></table></section></>}
    {toast&&<Toast message={toast} onDismiss={()=>setToast('')}/>}</>
}
