import { useState } from 'react';

import { FilterPanel } from '../../components/common/FilterPanel';
import { Modal } from '../../components/common/Modal';
import { PageHeader, SectionCard } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { SearchBar } from '../../components/common/SearchBar';
import { StatusBadge } from '../../components/common/StatusBadge';
import { Toast } from '../../components/common/Toast';
import { FormField } from '../../components/forms/FormField';
import { DataTable } from '../../components/tables/DataTable';
import { useTableControls } from '../../hooks/useTableControls';
import { generatedReports } from '../../data/notifications';
import { projects } from '../../data/projects';
import {
  REPORT_TYPES,
  type DataTableColumn,
  type ExportFormat,
  type FilterDefinition,
  type GeneratedReport,
} from '../../types';
import { formatDate } from '../../utils/format';
import { isValid, requiredField, type FieldErrors } from '../../utils/validation';

const FILTERS: FilterDefinition[] = [
  {
    id: 'type',
    label: 'Report type',
    options: REPORT_TYPES.map((value) => ({ label: value, value })),
  },
  {
    id: 'format',
    label: 'Format',
    options: ['PDF', 'Excel'].map((value) => ({ label: value, value })),
  },
  {
    id: 'status',
    label: 'Status',
    options: ['Ready', 'Generating', 'Failed'].map((value) => ({ label: value, value })),
  },
];

interface GenerateFormValues {
  type: string;
  projectName: string;
  periodFrom: string;
  periodTo: string;
  format: ExportFormat;
}

const EMPTY_FORM: GenerateFormValues = {
  type: '',
  projectName: 'All Projects',
  periodFrom: '',
  periodTo: '',
  format: 'PDF',
};

/**
 * Reports & Documentation — document module 10. Five report types plus PDF
 * and Excel export only (the document specifies no other formats). No Figma
 * screen existed for this module.
 */
export function ReportsPage() {
  const [modalOpen, setModalOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [values, setValues] = useState<GenerateFormValues>(EMPTY_FORM);
  const [errors, setErrors] = useState<FieldErrors<GenerateFormValues>>({});

  const controls = useTableControls<GeneratedReport>({
    rows: generatedReports,
    searchKeys: ['reportCode', 'type', 'projectName', 'generatedBy'],
    filterKeys: { type: 'type', format: 'format', status: 'status' },
    initialSortKey: 'generatedOn',
    initialSortDirection: 'desc',
    pageSize: 8,
  });

  function setField(field: keyof GenerateFormValues, value: string) {
    setValues((current) => ({ ...current, [field]: value }));
    setErrors((current) => ({ ...current, [field]: undefined }));
  }

  function handleGenerate(event: React.FormEvent) {
    event.preventDefault();

    const nextErrors: FieldErrors<GenerateFormValues> = {
      type: requiredField(values.type, 'Report type'),
      periodFrom: requiredField(values.periodFrom, 'Period start'),
      periodTo: requiredField(values.periodTo, 'Period end'),
    };

    setErrors(nextErrors);
    if (!isValid(nextErrors)) return;

    setToast(`${values.type} is being generated as ${values.format}.`);
    setValues(EMPTY_FORM);
    setModalOpen(false);
  }

  function handleExport(report: GeneratedReport) {
    if (report.status !== 'Ready') return;
    setToast(`Downloading ${report.reportCode} (${report.format})…`);
  }

  const columns: DataTableColumn<GeneratedReport>[] = [
    {
      key: 'reportCode',
      header: 'Report',
      sortable: true,
      width: '110px',
      render: (row) => <span className="bt-mono small bt-text-dim">{row.reportCode}</span>,
    },
    {
      key: 'type',
      header: 'Report type',
      sortable: true,
      render: (row) => (
        <div>
          <p className="mb-1 fw-semibold">{row.type}</p>
          <p className="bt-label mb-0">{row.projectName}</p>
        </div>
      ),
    },
    {
      key: 'periodFrom',
      header: 'Period',
      render: (row) => (
        <span className="bt-mono small">
          {formatDate(row.periodFrom)} — {formatDate(row.periodTo)}
        </span>
      ),
    },
    { key: 'generatedBy', header: 'Generated by', sortable: true },
    {
      key: 'generatedOn',
      header: 'Generated on',
      sortable: true,
      render: (row) => <span className="bt-mono small">{formatDate(row.generatedOn)}</span>,
    },
    {
      key: 'format',
      header: 'Format',
      sortable: true,
      render: (row) => (
        <span className="d-inline-flex align-items-center gap-2">
          <i
            className={`bi ${row.format === 'PDF' ? 'bi-file-earmark-pdf' : 'bi-file-earmark-spreadsheet'}`}
            style={{ color: row.format === 'PDF' ? 'var(--bt-red)' : 'var(--bt-green)' }}
            aria-hidden="true"
          />
          {row.format}
        </span>
      ),
    },
    {
      key: 'status',
      header: 'Status',
      sortable: true,
      render: (row) => <StatusBadge status={row.status} />,
    },
    {
      key: 'sizeKb',
      header: 'Action',
      align: 'end',
      width: '120px',
      render: (row) => (
        <button
          type="button"
          className="btn btn-outline-bt btn-sm"
          onClick={() => handleExport(row)}
          disabled={row.status !== 'Ready'}
        >
          <i className="bi bi-download me-1" aria-hidden="true" />
          Export
        </button>
      ),
    },
  ];

  return (
    <>
      <PageHeader
        title="Reports & Documentation"
        subtitle="Generate progress, resource, budget, workforce and procurement reports with PDF and Excel export."
        actions={
          <button type="button" className="btn btn-accent" onClick={() => setModalOpen(true)}>
            <i className="bi bi-file-earmark-plus me-2" aria-hidden="true" />
            Generate report
          </button>
        }
      />

      {/* Report type cards — the five document report types */}
      <div className="row g-3 g-lg-4 mb-4">
        {REPORT_TYPES.map((type, index) => {
          const count = generatedReports.filter((report) => report.type === type).length;
          const icons = [
            'bi-graph-up-arrow',
            'bi-truck-front',
            'bi-cash-coin',
            'bi-people',
            'bi-cart3',
          ];
          return (
            <div className="col-12 col-sm-6 col-xl" key={type}>
              <button
                type="button"
                className="bt-card bt-card-hover bt-card-pad w-100 text-start d-flex flex-column"
                onClick={() => {
                  setValues({ ...EMPTY_FORM, type });
                  setModalOpen(true);
                }}
              >
                <span className="bt-icon-tile bt-accent mb-3">
                  <i className={`bi ${icons[index]}`} aria-hidden="true" />
                </span>
                <p className="mb-1 fw-semibold" style={{ fontSize: '0.9rem' }}>
                  {type}
                </p>
                <p className="bt-label mb-0">{count} generated</p>
              </button>
            </div>
          );
        })}
      </div>

      <SectionCard
        title="Generated Reports"
        subtitle={`${controls.total} report${controls.total === 1 ? '' : 's'} in the current view`}
        flush
        actions={
          <>
            <SearchBar
              value={controls.search}
              onChange={controls.setSearch}
              placeholder="Search reports"
              label="Search reports"
              size="sm"
            />
            <FilterPanel
              filters={FILTERS}
              values={controls.filters}
              onChange={controls.setFilter}
              onClear={controls.clearFilters}
              activeCount={controls.activeFilterCount}
            />
          </>
        }
      >
        <DataTable
          columns={columns}
          rows={controls.pageRows}
          rowKey={(row) => row.id}
          sortKey={controls.sortKey}
          sortDirection={controls.sortDirection}
          onSort={controls.toggleSort}
          caption="Generated reports with format and status"
        />

        <hr className="bt-divider m-0" />

        <Pagination
          page={controls.page}
          pageCount={controls.pageCount}
          rangeStart={controls.rangeStart}
          rangeEnd={controls.rangeEnd}
          total={controls.total}
          itemLabel="Reports"
          onPageChange={controls.setPage}
        />
      </SectionCard>

      <Modal
        open={modalOpen}
        title="Generate report"
        description="Produce a report for a selected period and export it as PDF or Excel."
        onClose={() => setModalOpen(false)}
        footer={
          <>
            <button
              type="button"
              className="btn btn-outline-bt"
              onClick={() => setModalOpen(false)}
            >
              Cancel
            </button>
            <button type="submit" form="generate-report-form" className="btn btn-accent">
              Generate
            </button>
          </>
        }
      >
        <form id="generate-report-form" onSubmit={handleGenerate} noValidate>
          <div className="row g-3">
            <div className="col-12">
              <FormField
                as="select"
                label="Report type"
                value={values.type}
                onChange={(value) => setField('type', value)}
                options={REPORT_TYPES}
                error={errors.type}
                required
              />
            </div>

            <div className="col-12">
              <FormField
                as="select"
                label="Project"
                value={values.projectName}
                onChange={(value) => setField('projectName', value)}
                options={['All Projects', ...projects.map((project) => project.name)]}
                placeholderOption="Select project"
              />
            </div>

            <div className="col-12 col-md-6">
              <FormField
                type="date"
                label="Period from"
                value={values.periodFrom}
                onChange={(value) => setField('periodFrom', value)}
                error={errors.periodFrom}
                required
              />
            </div>

            <div className="col-12 col-md-6">
              <FormField
                type="date"
                label="Period to"
                value={values.periodTo}
                onChange={(value) => setField('periodTo', value)}
                error={errors.periodTo}
                required
              />
            </div>

            <div className="col-12">
              <FormField
                as="select"
                label="Export format"
                value={values.format}
                onChange={(value) => setField('format', value)}
                options={['PDF', 'Excel']}
                placeholderOption="Select format"
              />
            </div>
          </div>
        </form>
      </Modal>

      {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
    </>
  );
}
